version: "3.7"

x-yarpgpt: &yarpgpt
  image: fbrand-new/yarpgpt:devel
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
  network_mode: "host"
  privileged: true

services:
  yarpserver:
    <<: *yarpgpt
    command: sh -c "yarpserver --silent"
  yarpgpt:
    <<: *yarpgpt
    depends_on:
      - yarpserver
    command: sh -c "yarprobotinterface --context yarpGPT --config fakeLLMDevice.xml" 
  yarpgpttest:
    <<: *yarpgpt
    depends_on:
      - yarpgpt
    command: sh -c "cd /yarpGPT/tests; yarp wait /chat/rpc; python3 -m unittest integration/integration.py"