version: "3.7"

x-yarpgpt: &yarpgpt
  image: fbrand-new/yarpgpt:devel
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - XAUTHORITY=/root/.Xauthority
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "${XAUTHORITY}:/root/.Xauthority"
    - "${HOME}/.config/yarp:/root/.config/yarp"
  network_mode: "host"
  privileged: true
  env_file:
    - ../.env

services:
  yarpgpt:
    <<: *yarpgpt
    command: sh -c "yarprobotinterface --config /yarpGPT/app/conf/tryDevice.xml" 
  yarpgpttest:
    <<: *yarpgpt
    depends_on:
      - yarpgpt
    command: sh -c "cd /yarpGPT/build/gui; yarp wait /chat/rpc; ./gui"